scenarios:
  country: ['DE'] #, 'GR', 'GB', 'ES', 'SE'] #['EU', 'AL', 'AT', 'BA', 'BE', 'BG', 'CH', 'CZ', 'DE', 'DK', 'EE', 'ES', 'FI', 'FR', 'GB', 'GR', 'HR', 'HU', 'IE', 'IT', 'LT', 'LU', 'LV', 'ME', 'MK', 'NL', 'NO', 'PL', 'PT', 'RO', 'RS', 'SE', 'SI', 'SK']
  duration: [48] #[24, 48, 72]
  level: [0.06] #[0.06, 0.1, 0.15, 0.2]
  source: ['atlite'] #['ninja', 'atlite']
  exponent: [1] #[1,2]
  method: ['moving_average'] #['plain', 'mean_average', 'rolling_average', 'moving_average']
  corr: ['corrected'] #['uncorrected', 'corrected']
  mean_period: [6, 12, 24, 48]
  regimes: ['at', 'zo', 'sctr', 'ar', 'eubl', 'scbl', 'gl']
  met_variables: ['SOLD', 'T2M', 'W100M', 'SLP']
build_cutouts: false

cutout:
  module: era5
  xs: [2.0, 16.0]
  ys: [47.0, 56.0]
  years: [1979, 2018]

years: [1979, 2022]

technology:
  onwind:
    weight: 0.5
    resource:
      turbine: Vestas_V112_3MW
    fallback: #fallback values are chosen according to the values for Germany
      slope: 0.75
      intercept: 0.01
  solar:
    correction_factor: 1.
    weight: 0.44
    resource: 
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180. # South
    fallback:
      slope: 0.81
      intercept: 0.0
  offwind:
    weight: 0.06
    resource:
      turbine: NREL_ReferenceTurbine_5MW_offshore
    fallback:
      slope: 0.8
      intercept: 0.0

plotting:
  style: ggplot
  bins: [0, 24, 48, 72, 96, 120, 240]
  tech_colors:
    "solar": "#f9d002"
    "onwind": "#235ebc"
    "offwind": "#6823bc"
    "wind": "#2393bc"
    "combined": "#0c6013"
  regime_colors: 
    "AT": '#6100B3'
    "ZO": '#FB0005'
    "ScTr": '#FB6207'
    "AR": '#FECF0A'
    "EuBL": '#117B00'
    "ScBL": '#0B5300'
    "GL": '#0000FE'
    "No": '#6B6B6B'
